import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

// 1. IMPORT YOUR NEW FILE
import VisualEditingClient from "./VisualEditing";
import { draftMode } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 border-b border-gray-200 mb-4 flex justify-between items-center">
          <Link href="/" className="font-bold text-xl tracking-tighter">
            My Brand
          </Link>
          
          <div className="flex gap-6 text-sm font-medium text-gray-600">
            <Link href="/projects" className="hover:text-black">
              Portfolio
            </Link>
            <Link href="/about" className="hover:text-black">
              About
            </Link>
          </div>
        </nav>
        {children}
        
        {/* 2. USE YOUR WRAPPER HERE */}
        {isEnabled && <VisualEditingClient />}
        
      </body>
    </html>
  );
}